#
# Pičovína
#

# Name of your site (displayed in the header)
name: Bc et. Bc

# Short bio or description (displayed in the header)
description: Jak se stát dvojitým bakalářem

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: C:/Users/Malej/Desktop/1531982_10202701693562107_827209287_n.jpg

encoding: UTF-8

#
# Flags below are optional
