#
# Pičovína
#

# Name of your site (displayed in the header)
name: Bc et. Bc

# Short bio or description (displayed in the header)
description: Jak se stát dvojitým bakalářem

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://www.facebook.com/photo.php?fbid=10202701693562107&set=t.100000014019975&type=3&theater

#
# Flags below are optional
#


