#
# Pičovína
#

# Name of your site (displayed in the header)
name: Bakalář

# Short bio or description (displayed in the header)
description: Jak udělat z Davida dvojitého bakaláře

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://cs.wikipedia.org/wiki/Masarykova_univerzita#/media/File:Logo_Masaryk_University.svg

#
# Flags below are optional
#


